### ISSUE TITLE
 Provision Win Server for IIS/.NET Core 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureRM#1]
Provision Win Server for IIS/.NET Core 

Using the following script a base Windows 2012 R2 Server is created. 
https://github.com/stuartshay/AzureRM/blob/master/win-node/provision-win-server.ps1

The Server needs to be Provisioned with the necessary Tools & Software to Run a .NET Core Website
https://docs.asp.net/en/latest/publishing/iis.html

The Following Scripts were functional Scripts. 
https://github.com/stuartshay/AzureRM/tree/master/win-node/dsc

These Scripts are out of date using .NET/DNX which is no longer supported and need to be updated to lattest release of .NET Core

**Comment by stuartshay** [comment]
Load Testing 
http://www.hanselman.com/blog/TwoToolsForQuickAndEasyWebApplicationLoadTestingDuringDevelopment.aspx

**Comment by stuartshay** [comment]
Need to Manually Deploy - The Current Configuration is not correct

1) Use setup-iis-web.ps1 - To Compile Locally
`
```
  #Local File System
  Publish-AzureRmVMDscConfiguration -ConfigurationPath .\dsc\setup-iis-web.ps1 -OutputArchivePath ".\setup-iis-web.ps1.zip" -Force 
````
2) In the Azure Web SIte - Manually Upload Extension File

![untitled](https://cloud.githubusercontent.com/assets/887805/17653539/eb8e9cc6-6264-11e6-9dc5-210c76b2dc7f.png)
 
3) Use the Following Parameters 
````
FILE TO UPLOAD: setup-iis-web.ps1.zip
CONFIGURATIONFUNCTION: setup-iis-web.ps1\WebSite 
VERSION: 2.8
````

**Comment by stuartshay** [comment]
Add Install Module

      Package  DotNetCoreWindowsHostingInstall
      {
           Ensure = "Present"
           Path = "C:\setup\DotNetCore.1.0.0-WindowsHosting.exe"
           Name = "DotNetCore.1.0.0-WindowsHosting"
           ProductId = "4ADC4F4A-2D55-442A-8655-FBF619F94A69"
           DependsOn       = "[xRemoteFile]DotNetCoreWindowsHosting"
        }

**Comment by 4c74356b41** [comment]
I can switch it back to package provider, but during my test, dsc would fail because of the package provider. After dotnetcore install it would claim that a reboot is pending on a server and stop and wait for a reboot. that's why I switched to script resourse. I will convert to xremotefile resource + script one. I might also try with package resource again, but I don't think it will work...

**Comment by stuartshay** [comment]
Update Comment Above.   
The Powershell DSC Version might be the cause of the Errors, Need to find the lattest that works

**Comment by 4c74356b41** [comment]
I've uploaded next versión of dsc resource, it Works when you invoke it manually, but doesn't work from portal or powershell, i think I might créate an issue on azure side, because this doesn't really make sense

**Comment by stuartshay** [comment]
See the Notes Above
Need to use my script - setup-iis-web.ps1 

Install - DotNetCore.1.0.0-WindowsHosting.exe
Setup Website in IIS - There might be issues with permissions we can work out next

**Comment by stuartshay** [comment]
Cleaned up your script 
Use C:\Setup for Downloads 

Do not need to install SDK 
I think there might be permission issues on the Application also iisreset.exe might to be run after the install

Lets get this done and we can move on too new stuff I have which is allot

**Comment by 4c74356b41** [comment]
Yeah, iisreset is needed, but we can work around that by using another script dsc step with iisreset.
And I don't seen any problems with security.

**Comment by stuartshay** [comment]
win-web-server-dsc.ps1 - This is the original DSC Script 
setup-iis-web.ps1 - Need to get this working using the .NET Core 1.0

**Comment by 4c74356b41** [comment]
Script is working when invoked manually or invoked from Azure portal.

Using portal supply the following:
1. Zip File - Self explanatory.
2. Module-Qualified Name of Configuration - setup-iis-web.ps1\payload
3. Configuration Arguments - nodeName=localhost
4. Versión = 2.20
5. Allow minor versión updates true.

Leave  everything else as is

**Comment by stuartshay** [comment]
Closed  !!!
