### ISSUE TITLE
Provision Nano Server for IIS/.NET Core

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureRM#2]
Same as Issue #1 
https://github.com/stuartshay/AzureRM/blob/master/win-node/provision-nano-server.ps1

**Comment by 4c74356b41** [comment]
So i've uploaded to stuff to /nano folder
to invoke use dism /online /apply-unattend:.\unattend.xml
taken from here:
https://technet.microsoft.com/windows-server-docs/compute/nano-server/getting-started-with-nano-server#a-name-bkmk-online-a-installing-roles-and-features-online

**Comment by stuartshay** [comment]
As a Start We need a Script that will function like the other WinServer Scripts
Just build the Nano (No Features) 
It needs to use the existing storage, resource group 

On you end just rename the variables that are unique - Storage Account

**Comment by 4c74356b41** [comment]
just a powershell script to créate nano vm, so basically i just need to change image in the script and thats it?

**Comment by stuartshay** [comment]
Basic Install - Nothing Else 

This is the Format that needs to be done
https://github.com/stuartshay/AzureRM/blob/master/win-node/provision-nano-server.ps1

**Comment by 4c74356b41** [comment]
I don't understand I've just tested your script and it Works. Only thing I've done is change version to the latest - 2016.0.20160801
