### ISSUE TITLE
provision-ub-nginx.ps1

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureRM#4]
This is a Linux Host
See: provision-ub-nginx.ps1

1) Get Script Componets Working 

- [x] Create MOF File
- [x] Upload MOF File - Azure Blob Storage (Single File
- [x] Update Scripts  - Azure Blob Storage (Multiple Files)

2) Create VM 
- [x] VM Builds and Functional

3) Apply DSC Linux MOF
- [x]Install-mof.ps1 

![dsc failure](https://cloud.githubusercontent.com/assets/887805/18037101/e99c1dfe-6d49-11e6-99d2-9e8e6de33032.png)

4) Save Base Image and Cleanup  Image 
- [x] extract-ub.ps1

Notes:

**Comment by 4c74356b41** [comment]
OK, I've created 2 .ps1 scripts.
upload-scripts will upload all the files in ub-node (you have to point it to that folder) in storageaccount that you choose with relative dir paths.
uploda-mofs will upload zipped mof package to storage account and kick off azure dsc extensión

I didn't input any variables, but that can be done pretty fast.
Do you need créate a VM script or yours are fine?

**Comment by stuartshay** [comment]
Best to use my script - Might want to move the script so Win-Node can use this script.
I will review tonight 

From Just a Quick Look, It looks good

**Comment by stuartshay** [comment]
Need to go though all the steps 

When the MOF File is generated, Need to pass the Storage Account Parameter

See: provision-ub-nginx.ps1
````
#Create MOF File
./dsc/setup-nginx-proxy.ps1 -StorageAccountName $StorageAccountName 
````

**Comment by stuartshay** [comment]
When the Mof is created the Storage Account needs to be populated
See the Source path is blank in the output
````
ResourceID = "[nxFile]ProxyConf";
 DestinationPath = "/etc/nginx/sites-available/proxy";
 ModuleName = "nx";
 SourceInfo = "D:\\Documents\\GitHub\\AzureRM\\ub-node\\dsc\\setup-nginx-proxy.ps1::26::9::nxFile";
 ModuleVersion = "1.0";
 SourcePath = "https://.blob.core.windows.net/config/nginx.conf";

DependsOn = {

    "[nxPackage]Nginx"};

 ConfigurationName = "WebProxy";

};
````

**Comment by 4c74356b41** [comment]
Ok, I think I finally got your point (not about the storage account missing, but what you are trying to do generally). 
That script works now. provision-ub-nginx.ps1 (except for the DSC part). Also you should comment out UploadScripts if you only need to upload mof.

**Comment by stuartshay** [comment]
No Problem, As you can see I added more images, the goal is too get the images working 1st then build the network around the images,  (Using ARM Templates etc)

I do not run the entire script all at once, I usually update a script then upload the script and test the image.

The Reason for these steps and the duplicate scripts is that Nano, .NET Core etc they update versions every few months and also the ability latter on to add specific customization such as second disk or install some package.

I will test tonight, I am also working back on the web site so this will keep me busy, the Nano issue should be clear do the exact same thing we did for the Windows Server

**Comment by stuartshay** [comment]
Tested the Upload Mof - This is good,  big time saver

Here is what I need 
![scripts](https://cloud.githubusercontent.com/assets/887805/17944529/255e01ca-6a0e-11e6-8580-971176b49727.PNG)

**Comment by 4c74356b41** [comment]
well, upload scripts Works, but it uploads all the folder and files in the directory. So you need to specify how exactly you want it modified.

**Comment by stuartshay** [comment]
I think this will work,  but need to check if the Container already exists, throws error after created

````
#Upload Scripts
$UploadScripts = @{

    ResourceGroupName = $ResourceGroupName;    
    Location = $Location;
    StorageAccountName = $StorageAccountName;
    ContainerName = "nginx"
    PathToContent =".\config\nginx" 
};

.\upload-scripts.ps1 @UploadScripts
````

![capture](https://cloud.githubusercontent.com/assets/887805/17946633/29c0c9c4-6a17-11e6-9cbd-db4191c59656.PNG)

**Comment by 4c74356b41** [comment]
Ok, I'll do that tomorrow!

**Comment by stuartshay** [comment]
Cleaned Up Issue - 

- [ ] Apply DSC Linux MOF
- [ ] Save Base Image and Cleanup Image

**Comment by 4c74356b41** [comment]
Ok, I'm pretty sure that DSC expects localhost.mof instead of webproxy.mof
