### ISSUE TITLE
upload-scripts.ps1 - Enhancement

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureRM#7]
Moved the Script to util directory

If the Container does exist - Create it

**Comment by 4c74356b41** [comment]
it does exactly that, if the container doesnt exist - it creates it

**Comment by stuartshay** [comment]
Nope, Try it

**Comment by 4c74356b41** [comment]
fixed it, i added wrong parameters there, sorry.

**Comment by stuartshay** [comment]
Tested
First Time Run it Fails. Second Time Container is Created. 

I think it is best to replace functionality with this script 
https://gallery.technet.microsoft.com/scriptcenter/Copy-Files-from-a-Local-0b8de545

**Comment by 4c74356b41** [comment]
Well, i've added additional fix, but I've tested it like 10 times, it does work as expected.

**Comment by stuartshay** [comment]
Works Now - Going Forward we should use existing scripts.
Might be a good idea to use 
https://gallery.technet.microsoft.com/scriptcenter/Copy-Files-from-a-Local-0b8de545
